name: Daily BVB Scrape

# Run once per day at 8:00 AM UTC
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch: # allows manual run

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas beautifulsoup4 curl_cffi

      - name: Run scrape script
        run: |
          python scripts/scrape_bvb.py

      - name: Commit CSV files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add input/bvb_distribution/
          git commit -m "Update BVB CSV files (daily)"
          git push
        continue-on-error: true
